### ISSUE TITLE
 Cancel button will be nice idea in Edit Views and validation to not left empty 

### ISSUE THREAD

**Issue by kashiash** [twostraws/FaceFacts#2]
Empty rows on person list and event list when user enter to add new record and leave view without entering data<img width="408" alt="image" src="https://github.com/twostraws/FaceFacts/assets/10448372/1fccd9c6-9a6e-4b54-9272-e65335478f6c">

![image](https://github.com/twostraws/FaceFacts/assets/10448372/217cb0ce-73f3-483b-9ed6-b68e8dde724f)

**Comment by twostraws** [comment]
While I appreciate you filing issues, this repository is designed to accompany the video; it's not something I can easily change.
